### ISSUE TITLE
Build failed for Android

### ISSUE THREAD

**Issue by alfianakbar** [cyb3rcod3/flutter-openvidu-demo#1]
Thanks before for sharing!
I tried to build your code, but it failed in my android emulator. Could you help me?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:stripDebugDebugSymbols'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.1.6352462

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by cyb3rcod3** [comment]
What is your output of `flutter doctor -v` ?

Try this in [**android/build.grandle**](https://github.com/cyb3rcod3/flutter-openvidu-demo/blob/37666b5e63be12ee66a0a31a14a41ff5d3fd2d0b/android/build.gradle#L8)
`
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0' //Changed this
    }`

**Comment by cyb3rcod3** [comment]
Close

**Comment by cyb3rcod3** [comment]
Close
